### ISSUE TITLE
Receiver Phone Number Attribute - GatewayAPI.com requires an array

### ISSUE THREAD

**Issue by davidezordan25** [netzbegruenung/keycloak-mfa-plugins#100]
Hi,
I'm trying to implement your solution using our subscription to gatewayapi.com. According to their documentation (https://gatewayapi.com/docs/apis/rest/#basic-use), for the "Receiver Phone Number Attribute," they use "recipients" as an array of receivers. I've tried both "recipients" and "recipients.0.msisdn", but I received the following errors respectively:

2024-07-15 15:54:12,308 ERROR [netzbegruenung.keycloak.authenticator.gateway.SmsServiceFactory] (executor-thread-17) Failed to send message to 346xxxxxx [Response: {"fields":{"recipients":[{"sequencetypeinvalid":"Expected a list"}]}}
]. Validate your config.

2024-07-15 15:56:35,849 ERROR [netzbegruenung.keycloak.authenticator.gateway.SmsServiceFactory] (executor-thread-17) Failed to send message to 346xxxx [Response: {"fields":{"recipients":[{"requiredfieldinvalid":"Required key not provided"}]

**Comment by melegiul** [comment]
For the moment this API is not supported unfortunately, because it is not possible to send receivers as array. I guess we can further improve here, so that users can choose to send receivers as strings or as array. But we should still support the strings too, because there are providers that require them like: https://www.gtx-messaging.com/en/api-docs/sms-rest-api/

Related to: https://github.com/netzbegruenung/keycloak-mfa-plugins/issues/67

**Comment by davidezordan25** [comment]
As a workaround, i managed to make it compatible with the GatewayApi.com using the following configuration:

- enabled True in URL encode data
- SMS API URL: https://gatewayapi.com/rest/mtsms
- API Secret and basic auth username received in the dashboard of gatewayapi.com (API/credentials even if it's marked as deprecated)
- Message Atrribute: message
- Receiver Phone Number Attribute: recipients.0.msisdn
- Sender Phone Number Attribute: sender 

Besides, I also had to slightly modify in my local clone Java code in ApiSmsService.java in the prefix handling since GatewaySMS needs prefix in the format "39" e.g. for Italy, without + or other formats.

**Comment by melegiul** [comment]
This was solved in #126
