### ISSUE TITLE
PHONE VALIDATION action not working

### ISSUE THREAD

**Issue by phoenixtechnam** [netzbegruenung/keycloak-mfa-plugins#131]
Good day and thank you for your great work!

I am using the SMS authentication plugin together with Twilio and and works well to enforce 2FA via SMS.

However, when PHONE VALIDATION is active as required action, users cannot login anymore "Sorry, something went wrong"
The logs show this error message:
```
java.lang.NullPointerException: Cannot invoke "String.startsWith(String)" because "phone_number" is null
```

I activated "Set Phone Number as User attribute", but no attribute is created when a user creates the SMS 2FA via "update Mobile Number" required action. 

Maybe I am doing something wrong ? I would really love to have the validated phone number inside the user attributes...

Kindly assist, thank you in advance !

**Comment by melegiul** [comment]
Thank you for your report. But I think there is a misunderstanding in the use of the Required Action Phone Validation. So you try to assign this Required Action to users manually, right?

This is unfortunately not supported. Please do not assign this Required Action at any time. This action should only be triggered by Required Action Update Mobile Number.

If you want users to validate their existing numbers, you could only use the Required Action Update Mobile Number. There sits all the logic for proper number format validation: https://github.com/netzbegruenung/keycloak-mfa-plugins/blob/39152432bcbfdefb39c869d0ec88b2087209b8ac/sms-authenticator/src/main/java/netzbegruenung/keycloak/authenticator/PhoneNumberRequiredAction.java#L149

Downside is that they have to enter the phone number again. But that is the only supported option in the moment.

**Comment by melegiul** [comment]
Closing this for now. Feel free to reopen if the issue persists.
