### ISSUE TITLE
Consider adding this extension to the Keycloak community extension list 

### ISSUE THREAD

**Issue by ahus1** [netzbegruenung/keycloak-mfa-plugins#144]
There is a list of Keycloak community extension on Keycloak's homepage: https://www.keycloak.org/extensions.html

If you want this extension to be listed, please create a PR similar to this one: https://github.com/keycloak/keycloak-web/pull/517

**Comment by melegiul** [comment]
Thanks for reaching out! We're really excited about the chance to be listed on the Keycloak homepage. I've already asked for approval from my company, and once I get the go-ahead, I'll submit the PR following your example.

Looking forward to contributing to the Keycloak community!

**Comment by melegiul** [comment]
There it is: https://github.com/keycloak/keycloak-web/pull/527
