### ISSUE TITLE
Secret is in header and not body

### ISSUE THREAD

**Issue by egzj** [netzbegruenung/keycloak-mfa-plugins#173]
Hi guys.

I am trying to use InfoBip as the SMS provider but the API secret is in the Authorization header. 
```
curl -L -g 'https://xxx.api.infobip.com/sms/2/text/advanced' \
-H 'Authorization: App •••••••••••••••••9eb5' \
-H 'Content-Type: application/json' \
-H 'Accept: application/json' \
-d '{"messages":[{"destinations":[{"to":"6590000001"}],"from":"6590000001","text":"Congratulations on sending your first message. Go ahead and check the delivery report in the next step."}]
```

Any idea how to cater for it in the configuration?

**Comment by melegiul** [comment]
You could set the "API user" option, which will add an authorization header to the request.
https://github.com/netzbegruenung/keycloak-mfa-plugins/blob/4348a36dce7aab00b9e0056c26a8f96f8c59dda2/sms-authenticator/src/main/java/netzbegruenung/keycloak/authenticator/gateway/ApiSmsService.java#L89

**Comment by egzj** [comment]
`get_auth_header` is coded to use Basic Auth only and what I require is to send **App \<code\>** in the Authorization header. Guess I have to do some customisation. 

https://github.com/netzbegruenung/keycloak-mfa-plugins/blob/4348a36dce7aab00b9e0056c26a8f96f8c59dda2/sms-authenticator/src/main/java/netzbegruenung/keycloak/authenticator/gateway/ApiSmsService.java#L136

Thank @melegiul anyway, closing this
