### ISSUE TITLE
SMS Authenticator - Help needed in modifying the code.

### ISSUE THREAD

**Issue by RaveNN-0** [netzbegruenung/keycloak-mfa-plugins#174]
Hello,

I've used the SMS authenticator and it seems to work well for the most part.
In my case, we already have user phone numbers so I was trying to see where to change the code to go get the phone numbers from our endpoint but I can't seem to figure out where I should do the changes.

I thought about just modifying the "mobileNumber" variable in "SMSAuthenticaticator.java" and get the value from my endpoint but then I realised that I don't see the code pertaining to the "mobile_number_form.ftl" page. 
`mobileNumber = JsonSerialization.readValue(model.orElseThrow().getCredentialData(), SmsAuthCredentialData.class).getMobileNumber();`

I basically don't want to show the "Insert mobile number" page and go straight to the code verification by suplying the mobile number internally through our endpoint.

Best Regards,
RaveNN

**Comment by RaveNN-0** [comment]
-- Update -- 

- I put my code in "processAction"
- Changed "requiredActionChallenge" to generate a new form with just instructions and a "Get SMS Code" button.
- If the mobile number is not found on our internal endpoints, "handleInvalidNumber" is called and just defaults to the normal method where the user inserts his number.
- To avoid an infinite loop, as "processAction" is always used, a global boolean is used to determine when to fetch the data automatically and when to get the data from the HTTP request.

Any recommendations to make it better/more correct? I feel like this is kind of a band-aid solution.

**Comment by melegiul** [comment]
I never tried that yet. I would recommend to have a look at the database and the table credentials specifically. There are the phone number stored. You could sync that table with your API and disable the Required Actions "Set Mobile Number" which should prevent users from changing it via account console.
