### ISSUE TITLE
.jar Supporting Keycloak 24.0.1

### ISSUE THREAD

**Issue by tbaragao** [netzbegruenung/keycloak-mfa-plugins#68]
Keycloak launch a new major version containing the full implementation of user profile and progressive profiling.

Could you generate a new jar support this version?

**Comment by melegiul** [comment]
Support for keycloak 24 is still work in progress. I guess the release will be ready in the next weeks.

**Comment by dsputnikk** [comment]
Is it possible using 24.0 is related to: https://github.com/netzbegruenung/keycloak-mfa-plugins/issues/69#issuecomment-1998952886 ?

**Comment by melegiul** [comment]
Thanks again for your report. Release is now available: https://github.com/netzbegruenung/keycloak-mfa-plugins/releases/tag/v24.0.2
