### ISSUE TITLE
SMS 2FA plugin stuck in simulation mode

### ISSUE THREAD

**Issue by dsputnikk** [netzbegruenung/keycloak-mfa-plugins#72]
During testing I somehow managed to get my plugin stuck in "simulation" mode. I've gone as far as to destroy all custom flows and deleting the sms step. Saving. Coming back and readding the flow and ensuring simulation toggle is off. However when client initiates SMS flow, my console still shows **** SIMULATION MODE *** and I don't know how to turn it off now.

**Comment by melegiul** [comment]
When you have problems with switching the settings of the SMS Authenticator, then probably a hacky solution to access the Authenticator provider settings might be the reason. See https://github.com/netzbegruenung/keycloak-mfa-plugins/tree/main/sms-authenticator#setup

The config must be named "sms-2fa" (alias). If possible just use one SMS Authenticator together with its config in your flow. That would be the easiest option.

You could also use multiple Authenticators and Configs, but then you must keep in mind, that any time the SMS gateway is called by required actions (e.g. when user clicks on setup on account console) only your original config named "sms-2fa" matters.
