### ISSUE TITLE
TOTP name wrong in Enforce MFA dialog

### ISSUE THREAD

**Issue by svenseeberg** [netzbegruenung/keycloak-mfa-plugins#77]
The TOTP option seems to show a very generic title from https://github.com/keycloak/keycloak/blob/main/themes/src/main/resources-community/theme/base/email/messages/messages_de.properties#L29 instead of https://github.com/netzbegruenung/keycloak-mfa-plugins/blob/main/enforce-mfa/src/main/resources/theme-resources/messages/messages_de.properties#L5

Example:
![image](https://github.com/netzbegruenung/keycloak-mfa-plugins/assets/15197000/8217c40b-711c-4fb3-958c-c094a8d0064d)

**Comment by beezerk23** [comment]
Hey @svenseeberg , nothing to do with your topic but maybe could you share your flow configuration to get the screenshot? Currently my configuration looks like this: 
![Screenshot 2024-06-03 at 08 56 29](https://github.com/netzbegruenung/keycloak-mfa-plugins/assets/84435010/0de21a45-d059-4256-964e-8ee045faec92)

But for some reason i only see Passkey/FIDO2 as an option to choose.

Would highly appreciate an answer :)

**Comment by melegiul** [comment]
Hey @beezerk23,

when you see only Passkey as an option, the reason might be that the user already set up Passkey as 2FA.
Please make sure that all 2FA methods are removed from the user account.
Then during next login, you see the 2FA enforcement dialog after you submitted the password.

See also this (in the screenshot the second subflow should be actually conditional and not required):
https://github.com/netzbegruenung/keycloak-mfa-plugins/tree/main/enforce-mfa#how-to-use-this-authenticator

**Comment by beezerk23** [comment]
Hey @melegiul, where can i check if the user has already 2FA set? Its a completely new user so i think that will not be the case but just to be sure i would like to check. 

I think my configuration is exactly the same as in the screenshot you shared. Can you elaborate a bit more what i may miss?

**Comment by melegiul** [comment]
Yes, sure. You can make sure which 2FA are set for a user in the admin console. They would be listed under the password.

![image](https://github.com/netzbegruenung/keycloak-mfa-plugins/assets/47010475/3fa270ca-6772-4432-aade-c606541c8f41)

Another thing you should be aware of is, that the list of choices represents "required actions triggers". So you should also make sure that all related required actions are enabled on this page also in admin console: `/admin/master/console/#/master/authentication/required-actions`.

**Comment by beezerk23** [comment]
@melegiul That was it. I needed to activate the phone number action on required action. Now the SMS option is showing. Thanks!

**Comment by melegiul** [comment]
Im glad to hear that. You are welcome.

**Comment by melegiul** [comment]
> The TOTP option seems to show a very generic title from https://github.com/keycloak/keycloak/blob/main/themes/src/main/resources-community/theme/base/email/messages/messages_de.properties#L29 instead of https://github.com/netzbegruenung/keycloak-mfa-plugins/blob/main/enforce-mfa/src/main/resources/theme-resources/messages/messages_de.properties#L5
> 
> Example: ![image](https://private-user-images.githubusercontent.com/15197000/324845946-8217c40b-711c-4fb3-958c-c094a8d0064d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2NTgyODIsIm5iZiI6MTcxNzY1Nzk4MiwicGF0aCI6Ii8xNTE5NzAwMC8zMjQ4NDU5NDYtODIxN2M0MGItNzExYy00ZmIzLTk1OGMtYzA5NGE4ZDAwNjRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA2VDA3MTMwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhOWIyOTgxYzM2NjcxYTNlYWZhYTRjMmM3NDhkNjkwOTE5NDNhNmMzZTMxZmQwMDAxNDE3MWQzYjBlMzcyZmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7aNQdEdmFoXKqoUyD1JgwSeTmVxo2otMnJFTHI6VUS0)

Yes, that is right. It seems like we must take care ourselves to avoid any key conflicts with other SPIs. Actually only themes can override.
https://github.com/keycloak/keycloak/issues/11186#issuecomment-1111819696
