### ISSUE TITLE
Allow changing SMS texts via theme

### ISSUE THREAD

**Issue by svenseeberg** [netzbegruenung/keycloak-mfa-plugins#80]
I tried to configure the SMS text in the login theme. I added a line to the `themes/mytheme/login/messages/messages_de.properties` with `smsAuthText=My new message %1$s`. This new text was not used. Maybe it works with another trick, for example in the account theme. If that is the case, we should document it.

**Comment by melegiul** [comment]
The problem was caused by a duplicated entry for ' smsAuthText`. See https://git.verdigado.com/verdigado/keycloak-themes/pulls/20
