### ISSUE TITLE
SMS Logging

### ISSUE THREAD

**Issue by patmoshosting** [netzbegruenung/keycloak-mfa-plugins#81]
There are two issues with how SMS messages from Twilio are logged:
1. The plugin [only considers status code 200 as successful](https://github.com/netzbegruenung/keycloak-mfa-plugins/blob/main/sms-authenticator/src/main/java/netzbegruenung/keycloak/authenticator/gateway/ApiSmsService.java#L89), while Twilio uses status code 201 to indicate a success.
2. The plugin [logs the entire response body](https://github.com/netzbegruenung/keycloak-mfa-plugins/blob/main/sms-authenticator/src/main/java/netzbegruenung/keycloak/authenticator/gateway/ApiSmsService.java#L90) after a message is sent. Twilio includes the contents of the message in the response body, which means anyone who has access to the log files also has access to every 2FA code that is sent via SMS.

**Comment by melegiul** [comment]
Thanks a lot for your report. All response code with 2xx will now be considered successful. While the previous implementation should not make any harm, as the response code only decides about log level (info or error).

I also added a config option to hide the response body in the logs.
![image](https://github.com/netzbegruenung/keycloak-mfa-plugins/assets/47010475/612920d5-1df4-4fcd-b30e-21fec06b4d1b)
