### ISSUE TITLE
Use Lib Phonenumber 

### ISSUE THREAD

**Issue by alexanderhofstaetter** [netzbegruenung/keycloak-mfa-plugins#85]
It would be great to autoformat the number with https://github.com/google/libphonenumber and reject everything which is not `type=mobile`.  Also the nunber format can be normalized with this.

**Comment by svenseeberg** [comment]
Rejecting mobile numbers would have to be an optional setting, I think. In many cases land lines will probably work as some providers automatically create a phone call and read the SMS text.

**Comment by alexanderhofstaetter** [comment]
maybe add a config option to optionally add a "number type filter" -> add a comma seperated list of options which are valid:

see: https://github.com/google/libphonenumber/blob/b75f2937daea4e6a67cb91de7325061938df37bd/metadata/src/main/java/com/google/i18n/phonenumbers/metadata/Types.java#L22

so I would like to add a filter: MOBILE, FIXED_LINE_OR_MOBILE, PAGER

or optionally, there is a function for this: https://github.com/google/libphonenumber/blob/b75f2937daea4e6a67cb91de7325061938df37bd/java/carrier/src/com/google/i18n/phonenumbers/PhoneNumberToCarrierMapper.java#L117

**Comment by alexanderhofstaetter** [comment]
https://github.com/netzbegruenung/keycloak-mfa-plugins/pull/94
