### ISSUE TITLE
Allow SMS to be used as the primary (standalone) authenticator

### ISSUE THREAD

**Issue by Nefcanto** [netzbegruenung/keycloak-mfa-plugins#88]
Based on @svenseeberg [comment](https://github.com/keycloak/keycloak/discussions/20859#discussioncomment-9939471) I created this issue.

The main requirement for this plugin to be useful for the community is to abstract sending an SMS from the rest of the plugin. This can be done by a middle API provided by teams that use your plugin. This API would act as a proxy. Receives data from you by your contract, then sends it to a phone carrier.

We install your plugin. Then activate it and replace the current email/password form flow.
Then we somehow give you our API endpoint.

When the end user enters his phone number, you call our API with every parameter that's needed, including the realm, the phone number, the user id of the Keycloak, the OTP (or TOTP or any other code) that we should send to the end user.

This way you don't need to support myriads of phone carriers. You just create a contract. We create the API and connect it to our carriers.

Thank you

**Comment by svenseeberg** [comment]
I'm not 100% sure if I understand the problem correctly. We already have the following settings that basically allows you the send the SMS with an API call to your custom SMS proxy:

![image](https://github.com/netzbegruenung/keycloak-mfa-plugins/assets/15197000/513c6c64-bbc1-43b8-ae55-5526cdc1b5a0)

That means you can already configure a URL, authentication & attribute names for the message, the receiving and sending phone number.

Mostly missing is currently a HTTP GET option, which would be relatively easy to implement. See #67 for reference.

**Comment by Nefcanto** [comment]
@svenseeberg thank you for the explanation. The first point prior to this configuration is that your plugin is for 2FA or MFA.

Can you extend it to be used as one-factor authentication? I want to use your plugin, and this is the login scenario:

1. The user comes to the sign-in page
2. He enters his phone number
3. You call my API
4. I send the OTP to the user
5. The user enters the OTP
6. He gets signed in

This means that we don't have a sign-up. Sign-up and sign-in are both the same thing. If the user requests the OTP for the first time, that means registration (phone number would become the user name, password can be empty).

**Comment by svenseeberg** [comment]
AFAICT currently it is not possible to use this SMS plugin as a standalone authentication step. This is a generic problem that also affects Webauthn, see https://github.com/keycloak/keycloak/issues/12102.

However, you can create a authentication flow that first asks the user for a username (without password) and then only for the SMS. IMHO that should work.

**Comment by Nefcanto** [comment]
@svenseeberg, thank you for your time. The point is when we ask users for their usernames, it defies our main purpose in the first place: the simplicity of login. Phone/OTP login is simple though it's less secure.

**Comment by Nefcanto** [comment]
> *edit: You could, of course, store the phone number in the username field. With https://github.com/netzbegruenung/keycloak-mfa-plugins/issues/84 you could then implement the workflow as you described.

@svenseeberg I saw your edit recently. That would be awesome. We will have a form for phone number (which will be stored as the username). This will be the workflow. Can you please verify it?

- The user comes to the signup/sign-in page. They are both the same, even if they have different URLs and forms. But from the perspective of the user, they don't differ.
- The user sees a single input. It's not named "username". It's named "Phone number".
- Phone number is entered. No validation. Just ensuring that it's numeric.
- On clicking the submit button, if the user already exists, an OTP will be sent for it. If the user is new, first a user would be created for that phone number as the username, and then an OTP will be sent.
- On the next page, the OTP would be entered
- On submitting the second form, the user would be signed in

Can you please verify that your plugin works for this flow? If so, I will gladly install it.

Thank you.

**Comment by ar-or** [comment]
I was not able to configure it that way.

<img width="2311" height="354" alt="Image" src="https://github.com/user-attachments/assets/fe54d4e8-e2dc-44cd-928c-717d44ca0d4d" />

Resulting in
`Cannot login, credential setup required.`
