### ISSUE TITLE
SMS MFA Documentation

### ISSUE THREAD

**Issue by svenseeberg** [netzbegruenung/keycloak-mfa-plugins#90]
We need documentation about how to set up the SMS Authenticator. https://medium.com/@bkamaraj/implementing-mfa-using-sms-otp-in-keycloak-0444d1468ec1 is also worth a link.

**Comment by melegiul** [comment]
We already have documentation here: https://github.com/netzbegruenung/keycloak-mfa-plugins/blob/main/sms-authenticator/README.md

**Comment by svenseeberg** [comment]
True, I forgot about that. We should then either move it to the docs directory or alternatively move the files from there to the relevant plugin subdirectories.
